# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages


on:
  # Runs on pushes targeting the default branch
  push:
    paths:
      - 'server-render/**'
      - 'gh-pages/**'
    branches:
      - "master"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write


# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true


env:
  clojure-cli: "latest"
  java-version: "17"
  node-version: "17"


jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.java-version }}
      - name: Preparation
        run: |
          cp .ci/settings.xml ~/.m2/settings.xml
          mvn dependency:get -Dartifact=org.apache.maven.plugins:maven-deploy-plugin:2.8
      - name: Set up clojure-cli
        uses: DeLaGuardo/setup-clojure@9.4
        with:
          cli: ${{ env.clojure-cli }}
      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-${{ runner.os }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            cljdeps-${{ runner.os }}-


      - name: Render gh-pages
        run: |
          clojure -T:build/gh-pages clean
          clojure -X:test:release
          clojure -T:build/gh-pages all


      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './gh-pages'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
